Vagrant.configure("2") do |config|
  config.vm.define "nfs-server" do |m|
      m.vm.box = "ubuntu/bionic64"
      m.vm.hostname = "nfs-server"
      m.vm.provision "shell", path: "nfs-server.sh"
      m.vm.network "forwarded_port", guest: 80, host: 8080
      m.vm.network "private_network", ip: "192.168.33.10"
      m.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--memory', '1024' ]
        vb.customize [ 'modifyvm', :id, '--name', 'nfs-server' ]
        vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', '30' ]
      end
  end
  config.vm.define "nfs-client-01" do |m|
      m.vm.box = "ubuntu/xenial64"
      m.vm.hostname = "nfs-client-01"
      m.vm.provision "shell", path: "nfs-client.sh"
      m.vm.network "private_network", ip: "192.168.33.11"
      m.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--memory', '512' ]
        vb.customize [ 'modifyvm', :id, '--name', 'nfs-client-01' ]
        vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', '30' ]
      end
  end
  config.vm.define "nfs-client-02" do |m|
      m.vm.box = "ubuntu/xenial64"
      m.vm.hostname = "nfs-client-02"
      m.vm.provision "shell", path: "nfs-client.sh"
      m.vm.network "private_network", ip: "192.168.33.11"
      m.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--memory', '512' ]
        vb.customize [ 'modifyvm', :id, '--name', 'nfs-client-02' ]
        vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', '30' ]
      end
  end
end
